# Site settings

title: dan yawitz # Title of your site
email: daniel.yawitz@gmail.com # Your contant email

description: Playing with data until I can tell you something new

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar

twitter_username:     yawitzd  # Replace this with your Twitter username
github_username:      yawitzd  # Replace this with your GitHub username
linkedin_username:    https://www.linkedin.com/in/danielyawitz
  # Replace this with your LinkedIn username
google_plus_username: #example  # Replace this with your Google+ username
facebook_username:    #example  # Replace this with your Facebook username
dribbble_username:    #example  # Replace this with your Dribbble username

google_analytics: UA-72306634-1

# Build settings
markdown: kramdown

exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME
